server:
  port: 8081

spring:
  main:
    banner-mode: off

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

app:
  scheduling:
    enable: true